### ISSUE TITLE
ValueError: Cannot feed value of shape (0,) for Tensor 'Placeholder:0', which has shape '(12, 16, 160, 160, 3)'

### ISSUE THREAD

**Issue by AndyHon** [yfxc/pseudo-3d-tensorflow#6]
I met the following problem, how should I solve it？thanks
Traceback (most recent call last):
  File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 141, in <module>
    run()
  File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 119, in run
    label_placeholder:train_labels})
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1116, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor 'Placeholder:0', which has shape '(12, 16, 160, 160, 3)'

**Comment by AndyHon** [comment]
I have solved this problem, but I have a new one.
It is always one less than batch_size, sometimes two. I don't know why. please help me.
Traceback (most recent call last):
  File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 142, in <module>
    run()
  File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 120, in run
    label_placeholder:train_labels})
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1116, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (11, 16, 160, 160, 3) for Tensor 'Placeholder:0', which has shape '(12, 16, 160, 160, 3)'

**Comment by yfxc** [comment]
> I have solved this problem, but I have a new one.
> It is always one less than batch_size, sometimes two. I don't know why. please help me.
> Traceback (most recent call last):
> File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 142, in 
> run()
> File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 120, in run
> label_placeholder:train_labels})
> File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
> run_metadata_ptr)
> File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1116, in _run
> str(subfeed_t.get_shape())))
> ValueError: Cannot feed value of shape (11, 16, 160, 160, 3) for Tensor 'Placeholder:0', which has shape '(12, 16, 160, 160, 3)'



> I have solved this problem, but I have a new one.
> It is always one less than batch_size, sometimes two. I don't know why. please help me.
> Traceback (most recent call last):
> File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 142, in 
> run()
> File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 120, in run
> label_placeholder:train_labels})
> File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
> run_metadata_ptr)
> File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1116, in _run
> str(subfeed_t.get_shape())))
> ValueError: Cannot feed value of shape (11, 16, 160, 160, 3) for Tensor 'Placeholder:0', which has shape '(12, 16, 160, 160, 3)'



> I have solved this problem, but I have a new one.
> It is always one less than batch_size, sometimes two. I don't know why. please help me.
> Traceback (most recent call last):
> File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 142, in 
> run()
> File "/home/p18301147/pseudo-3d-tensorflow/train.py", line 120, in run
> label_placeholder:train_labels})
> File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
> run_metadata_ptr)
> File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1116, in _run
> str(subfeed_t.get_shape())))
> ValueError: Cannot feed value of shape (11, 16, 160, 160, 3) for Tensor 'Placeholder:0', which has shape '(12, 16, 160, 160, 3)'

Please change the parameter before you have built the tensorflow graph.
